@extends('layouts.skydash')
@section('content')
<x-ui.breadcrumb :items="[['label' => 'Gudang', 'url' => route('warehouses.index')], ['label' => $warehouse->nama_gudang]]" />
<x-ui.page-header title="Detail Gudang" description="Informasi gudang dan stok per barang."><div class="page-actions"><x-ui.button :href="route('warehouses.index')" variant="outline-secondary" icon="ti-arrow-left">Kembali</x-ui.button>@can('manage-barang')<x-ui.button :href="route('warehouses.edit', $warehouse)" icon="ti-pencil">Edit Gudang</x-ui.button>@endcan</div></x-ui.page-header>
@if(session('success'))<x-ui.alert type="success" dismissible>{{ session('success') }}</x-ui.alert>@endif
<div class="stats-grid master-stats-grid"><x-ui.card class="stat-card stat-info"><div class="stat-icon"><i class="ti-package"></i></div><p>Total Jenis Barang</p><strong>{{ number_format($totalJenisBarang, 0, ',', '.') }}</strong><small>Baris stok di gudang</small></x-ui.card><x-ui.card class="stat-card stat-success"><div class="stat-icon"><i class="ti-layers"></i></div><p>Total Kuantitas</p><strong>{{ number_format($totalKuantitas, 0, ',', '.') }}</strong><small>Seluruh unit tersimpan</small></x-ui.card></div>
<x-ui.card class="mb-4"><div class="row"><div class="col-md-4 mb-3"><p class="detail-label">Kode Gudang</p><p class="detail-value"><x-ui.badge variant="primary">{{ $warehouse->kode_gudang }}</x-ui.badge></p></div><div class="col-md-4 mb-3"><p class="detail-label">Nama Gudang</p><p class="detail-value">{{ $warehouse->nama_gudang }}</p></div><div class="col-md-4 mb-3"><p class="detail-label">Status</p><p class="detail-value"><x-ui.badge :variant="$warehouse->is_active ? 'success' : 'secondary'">{{ $warehouse->is_active ? 'Aktif' : 'Nonaktif' }}</x-ui.badge></p></div><div class="col-md-6"><p class="detail-label">Alamat</p><p class="detail-value text-preline">{{ $warehouse->alamat ?: '—' }}</p></div><div class="col-md-6"><p class="detail-label">Keterangan</p><p class="detail-value text-preline">{{ $warehouse->keterangan ?: '—' }}</p></div></div></x-ui.card>
<x-ui.card><div class="table-heading"><div><h2>Stok Gudang</h2><p>Data stok dari warehouse_stocks</p></div></div><div class="table-responsive"><table class="table inventory-table"><thead><tr><th>Kode Barang</th><th>Nama Barang</th><th class="text-end">Stok</th><th class="text-end">Stok Minimum</th><th>Status</th></tr></thead><tbody>@forelse($stocks as $stock)<tr><td>@if($stock->barang)<a href="/barang/{{ $stock->barang->id }}">{{ $stock->barang->kode_barang }}</a>@else — @endif</td><td>{{ $stock->barang?->nama_barang ?: 'Barang tidak tersedia' }}</td><td class="text-end">{{ number_format($stock->stok, 0, ',', '.') }} {{ $stock->barang?->satuan }}</td><td class="text-end">{{ number_format($stock->stok_minimum, 0, ',', '.') }} {{ $stock->barang?->satuan }}</td><td><x-ui.badge :variant="$stock->stok <= $stock->stok_minimum ? 'danger' : 'success'">{{ $stock->stok <= $stock->stok_minimum ? 'Menipis' : 'Aman' }}</x-ui.badge></td></tr>@empty<tr><td colspan="5"><x-ui.empty-state icon="ti-package" title="Belum ada stok" description="Belum ada stok barang yang tercatat di gudang ini." /></td></tr>@endforelse</tbody></table></div>@if($stocks->hasPages())<div class="pagination-wrap">{{ $stocks->onEachSide(1)->links() }}</div>@endif</x-ui.card>
@endsection
