@extends('layouts.skydash')
@section('content')
<div class="page-header"><div><h3 class="font-weight-bold">Persediaan Barang</h3><p>Kelola data dan stok barang gudang Anda.</p></div><div><a href="{{ route('barang.export.pdf') }}" class="btn btn-danger"><i class="ti-file"></i> Cetak PDF Laporan Stok</a> <a href="{{ route('barang.export.excel') }}" class="btn btn-success"><i class="ti-export"></i> Export Excel</a> <a href="{{ route('barang.trash') }}" class="btn btn-warning"><i class="ti-trash"></i> Tong Sampah</a> <a href="/barang/create" class="btn btn-primary"><i class="ti-plus me-1"></i> Tambah Barang</a></div></div>
@if(session('success'))<div class="alert alert-success alert-dismissible fade show" role="alert">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
<div class="row">
  <div class="col-md-6 col-xl-3 grid-margin stretch-card"><div class="card card-tale stat-card"><div class="card-body"><i class="icon-box float-end stat-icon"></i><p class="mb-4">Total Jenis Barang</p><p class="fs-30 mb-0">{{ $totalJenis }}</p></div></div></div>
  <div class="col-md-6 col-xl-3 grid-margin stretch-card"><div class="card card-dark-blue stat-card"><div class="card-body"><i class="icon-layers float-end stat-icon"></i><p class="mb-4">Total Unit Stok</p><p class="fs-30 mb-0">{{ $totalStok }}</p></div></div></div>
  <div class="col-md-6 col-xl-3 grid-margin stretch-card"><div class="card card-light-blue stat-card"><div class="card-body"><i class="icon-tag float-end stat-icon"></i><p class="mb-4">Kategori Barang</p><p class="fs-30 mb-0">{{ $totalKategori }}</p></div></div></div>
  <div class="col-md-6 col-xl-3 grid-margin stretch-card"><div class="card card-light-danger stat-card"><div class="card-body"><i class="icon-alert float-end stat-icon"></i><p class="mb-4">Stok Menipis (≤ 5)</p><p class="fs-30 mb-0">{{ $stokMenipis }}</p></div></div></div>
</div>
<div class="card toolbar-card mb-4"><div class="card-body"><form action="/barang" method="GET" class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Pencarian</label><input class="form-control" type="text" name="search" placeholder="Kode, nama, atau lokasi" value="{{ request('search') }}"></div><div class="col-md-3"><label class="form-label">Kategori</label><select class="form-select" name="kategori"><option value="">Semua Kategori</option>@foreach($kategori_options as $kategori)<option value="{{ $kategori }}" @selected(request('kategori') == $kategori)>{{ $kategori }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Urutkan</label><select class="form-select" name="sort"><option value="">Urutkan data</option><option value="nama_asc" @selected(request('sort') === 'nama_asc')>Nama A-Z</option><option value="nama_desc" @selected(request('sort') === 'nama_desc')>Nama Z-A</option><option value="stok_asc" @selected(request('sort') === 'stok_asc')>Stok Terkecil</option><option value="stok_desc" @selected(request('sort') === 'stok_desc')>Stok Terbesar</option></select></div><div class="col-md-2"><button type="submit" class="btn btn-outline-primary w-100"><i class="icon-search me-1"></i>Cari</button></div></form></div></div>
<div class="card"><div class="card-body"><h4 class="card-title">Daftar Barang</h4><div class="table-responsive"><table class="table table-hover"><thead><tr><th>No.</th><th>Foto</th><th>Kode Barang</th><th>Nama Barang</th><th>Kategori</th><th>Stok</th><th>Lokasi</th><th>Aksi</th></tr></thead><tbody>@forelse($barang as $index => $item)<tr><td>{{ $barang->firstItem() + $index }}</td><td><img src="{{ $item->foto_barang ? asset('storage/' . $item->foto_barang) : 'https://placehold.co/50x50?text=No+Image' }}" alt="{{ $item->nama_barang }}" width="45" height="45" class="rounded style-object-fit" style="object-fit: cover;"></td><td><span class="badge badge-info">{{ $item->kode_barang }}</span></td><td><strong>{{ $item->nama_barang }}</strong><small class="d-block text-muted">{{ $item->satuan }}</small></td><td><span class="badge badge-info">{{ $item->kategori }}</span></td><td><span class="font-weight-bold {{ $item->stok <= 5 ? 'text-danger' : '' }}">{{ $item->stok }} {{ $item->satuan }}</span></td><td>{{ $item->lokasi }}</td><td><div class="table-actions"><a href="/barang/{{ $item->id }}" class="btn btn-sm btn-inverse-primary">Detail</a><a href="/barang/{{ $item->id }}/edit" class="btn btn-sm btn-inverse-warning">Edit</a>@can('delete', $item)
<form action="/barang/{{ $item->id }}" method="POST" onsubmit="return confirm('Yakin ingin menghapus barang ini?')">
    @csrf
    @method('DELETE')
    <button class="btn btn-sm btn-inverse-danger" type="submit">Hapus</button>
</form>
@endcan</div></td></tr>@empty<tr><td colspan="8"><div class="empty-state"><i class="icon-box d-block mb-2"></i>Data barang tidak ditemukan.</div></td></tr>@endforelse</tbody></table></div>@if($barang->hasPages())<nav class="d-flex justify-content-center mt-4" aria-label="Navigasi halaman"><ul class="pagination pagination-sm mb-0"><li class="page-item {{ $barang->onFirstPage() ? 'disabled' : '' }}">@if($barang->onFirstPage())<span class="page-link" aria-hidden="true">‹</span>@else<a class="page-link" href="{{ $barang->previousPageUrl() }}" aria-label="Halaman sebelumnya">‹</a>@endif</li>@foreach($barang->getUrlRange(max(1, $barang->currentPage() - 2), min($barang->lastPage(), $barang->currentPage() + 2)) as $page => $url)<li class="page-item {{ $page === $barang->currentPage() ? 'active' : '' }}"><a class="page-link" href="{{ $url }}">{{ $page }}</a></li>@endforeach<li class="page-item {{ $barang->hasMorePages() ? '' : 'disabled' }}">@if($barang->hasMorePages())<a class="page-link" href="{{ $barang->nextPageUrl() }}" aria-label="Halaman berikutnya">›</a>@else<span class="page-link" aria-hidden="true">›</span>@endif</li></ul></nav>@endif</div></div>
@endsection
