<div class="row">
    <div class="col-md-6"><div class="form-group"><label class="form-label" for="kode_supplier">Kode Supplier</label><input class="form-control @error('kode_supplier') is-invalid @enderror" id="kode_supplier" name="kode_supplier" value="{{ old('kode_supplier', $supplier->kode_supplier ?? '') }}" maxlength="255" required autofocus>@error('kode_supplier')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label class="form-label" for="nama_supplier">Nama Supplier</label><input class="form-control @error('nama_supplier') is-invalid @enderror" id="nama_supplier" name="nama_supplier" value="{{ old('nama_supplier', $supplier->nama_supplier ?? '') }}" maxlength="255" required>@error('nama_supplier')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
</div>
<div class="row">
    <div class="col-md-4"><div class="form-group"><label class="form-label" for="contact_person">Contact Person</label><input class="form-control @error('contact_person') is-invalid @enderror" id="contact_person" name="contact_person" value="{{ old('contact_person', $supplier->contact_person ?? '') }}" maxlength="255">@error('contact_person')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-4"><div class="form-group"><label class="form-label" for="telepon">Telepon</label><input class="form-control @error('telepon') is-invalid @enderror" id="telepon" name="telepon" type="tel" value="{{ old('telepon', $supplier->telepon ?? '') }}" maxlength="255">@error('telepon')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-4"><div class="form-group"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $supplier->email ?? '') }}" maxlength="255">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
</div>
<div class="form-group"><label class="form-label" for="alamat">Alamat</label><textarea class="form-control @error('alamat') is-invalid @enderror" id="alamat" name="alamat" rows="3">{{ old('alamat', $supplier->alamat ?? '') }}</textarea>@error('alamat')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="form-group"><input type="hidden" name="is_active" value="0"><div class="form-check"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked((bool) old('is_active', $supplier->is_active ?? true))><label class="form-check-label" for="is_active">Supplier aktif</label></div>@error('is_active')<div class="text-danger small">{{ $message }}</div>@enderror</div>
<div class="d-flex flex-wrap justify-content-end gap-2"><x-ui.button :href="route('suppliers.index')" variant="light">Batal</x-ui.button><x-ui.button type="submit" icon="ti-save">{{ $submitLabel }}</x-ui.button></div>
