<div class="row">
    <div class="col-md-8"><div class="form-group"><label for="kode_barang" class="form-label">Kode Barang</label><input type="text" id="kode_barang" class="form-control" value="{{ $barang->kode_barang ?? $nextCodePreview }}" readonly aria-describedby="kodeBarangHelp"><div class="form-text" id="kodeBarangHelp">@isset($barang)Kode barang tidak dapat diubah setelah disimpan.@else Kode dibuat otomatis oleh sistem dengan format BRG-000001. Preview dapat berubah jika ada transaksi lain sebelum data disimpan.@endisset</div></div></div>
    <div class="col-md-4"><div class="form-group"><label for="stok" class="form-label">{{ isset($barang) ? 'Stok' : 'Stok Awal' }}</label><input type="number" id="stok" name="stok" class="form-control @error('stok') is-invalid @enderror" min="0" value="{{ old('stok', $barang->stok ?? 10) }}" required>@error('stok')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
</div>
<div class="form-group"><label for="nama_barang" class="form-label">Nama Barang</label><input type="text" id="nama_barang" name="nama_barang" class="form-control @error('nama_barang') is-invalid @enderror" placeholder="Contoh: Router Wi-Fi AC1200" value="{{ old('nama_barang', $barang->nama_barang ?? '') }}" required>@error('nama_barang')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="row">
    <div class="col-md-6"><div class="form-group"><label for="kategori" class="form-label">Kategori</label><input type="text" id="kategori" name="kategori" list="kategori_list" class="form-control @error('kategori') is-invalid @enderror" value="{{ old('kategori', $barang->kategori ?? '') }}" required><datalist id="kategori_list">@foreach($kategori_options as $kat)<option value="{{ $kat }}"></option>@endforeach</datalist>@error('kategori')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label for="satuan" class="form-label">Satuan</label><input type="text" id="satuan" name="satuan" list="satuan_list" class="form-control @error('satuan') is-invalid @enderror" value="{{ old('satuan', $barang->satuan ?? 'Unit') }}" required><datalist id="satuan_list">@foreach($satuan_options as $sat)<option value="{{ $sat }}"></option>@endforeach</datalist>@error('satuan')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
</div>
<div class="form-group"><label for="lokasi" class="form-label">Lokasi Penyimpanan</label><input type="text" id="lokasi" name="lokasi" class="form-control @error('lokasi') is-invalid @enderror" placeholder="Contoh: Gudang A, Rak B2" value="{{ old('lokasi', $barang->lokasi ?? '') }}" required>@error('lokasi')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="form-group"><label for="foto_barang" class="form-label">Foto Barang</label><input type="file" id="foto_barang" name="foto_barang" class="form-control @error('foto_barang') is-invalid @enderror" accept="image/jpeg,image/png,image/webp" aria-describedby="fotoHelp">@error('foto_barang')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text" id="fotoHelp">JPG, PNG, atau WebP maksimal 2 MB.@isset($barang) Kosongkan jika foto tidak diubah.@endisset</div>@if(isset($barang) && $barang->foto_barang)<img class="barang-photo-preview mt-2" src="{{ Storage::url($barang->foto_barang) }}" alt="Foto {{ $barang->nama_barang }}">@endif</div>
<div class="d-flex flex-wrap justify-content-end gap-2"><x-ui.button :href="route('barang.index')" variant="light">Batal</x-ui.button><x-ui.button type="submit" icon="ti-save">{{ $submitLabel }}</x-ui.button></div>
