<div class="row">
    <div class="{{ isset($barang) ? 'col-12' : 'col-md-8' }}"><div class="form-group"><label for="kode_barang" class="form-label">Kode Barang</label><input type="text" id="kode_barang" class="form-control" value="{{ $barang->kode_barang ?? $nextCodePreview }}" readonly aria-describedby="kodeBarangHelp"><div class="form-text" id="kodeBarangHelp">@isset($barang)Kode barang tidak dapat diubah setelah disimpan.@else Kode dibuat otomatis oleh sistem dengan format BRG-000001. Preview dapat berubah jika ada transaksi lain sebelum data disimpan.@endisset</div></div></div>
    @unless(isset($barang))<div class="col-md-4"><div class="form-group"><label for="stok" class="form-label">Stok Awal</label><input type="number" id="stok" name="stok" class="form-control @error('stok') is-invalid @enderror" min="0" value="{{ old('stok', 10) }}" required>@error('stok')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>@endunless
</div>
@unless(isset($barang))<div class="form-group"><label for="warehouse_id" class="form-label">Gudang Stok Awal</label>@if($warehouse_options->isNotEmpty())<select id="warehouse_id" name="warehouse_id" class="form-select @error('warehouse_id') is-invalid @enderror" aria-describedby="initialWarehouseHelp"><option value="">Pilih Gudang</option>@foreach($warehouse_options as $warehouse)<option value="{{ $warehouse->id }}" @selected((string) old('warehouse_id') === (string) $warehouse->id)>{{ $warehouse->kode_gudang }} · {{ $warehouse->nama_gudang }}</option>@endforeach</select><div class="form-text" id="initialWarehouseHelp">Wajib jika stok awal lebih dari 0. Jika stok awal 0, gudang boleh dikosongkan atau dipilih untuk menyiapkan saldo.</div>@error('warehouse_id')<div class="invalid-feedback">{{ $message }}</div>@enderror @else<x-ui.alert type="warning">Belum ada Gudang aktif. Stok awal hanya dapat disimpan dengan nilai 0. <a href="{{ route('warehouses.index') }}">Buka Master Gudang</a>.</x-ui.alert>@endif</div>@endunless
<div class="form-group"><label for="nama_barang" class="form-label">Nama Barang</label><input type="text" id="nama_barang" name="nama_barang" class="form-control @error('nama_barang') is-invalid @enderror" placeholder="Contoh: Router Wi-Fi AC1200" value="{{ old('nama_barang', $barang->nama_barang ?? '') }}" required>@error('nama_barang')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="form-group"><label for="supplier_id" class="form-label">Supplier Barang</label><select id="supplier_id" name="supplier_id" class="form-select @error('supplier_id') is-invalid @enderror" aria-describedby="supplierHelp"><option value="">Tanpa Supplier</option>@if(isset($barang) && $barang->supplier && (!$barang->supplier->is_active || $barang->supplier->trashed()))<option value="{{ $barang->supplier_id }}" @selected((string) old('supplier_id', $barang->supplier_id) === (string) $barang->supplier_id)>Pertahankan supplier tersimpan (tidak aktif)</option>@endif @foreach($supplier_options as $supplier)<option value="{{ $supplier->id }}" @selected((string) old('supplier_id', $barang->supplier_id ?? '') === (string) $supplier->id)>{{ $supplier->kode_supplier }} · {{ $supplier->nama_supplier }}</option>@endforeach</select><div class="form-text" id="supplierHelp">Opsional. Hanya supplier aktif yang dapat dipilih untuk data baru.</div>@error('supplier_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="row">
    <div class="col-md-6"><div class="form-group"><label for="kategori" class="form-label">Kategori</label><input type="text" id="kategori" name="kategori" list="kategori_list" class="form-control @error('kategori') is-invalid @enderror" value="{{ old('kategori', $barang->kategori ?? '') }}" required><datalist id="kategori_list">@foreach($kategori_options as $kat)<option value="{{ $kat }}"></option>@endforeach</datalist>@error('kategori')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
    <div class="col-md-6"><div class="form-group"><label for="satuan" class="form-label">Satuan</label><input type="text" id="satuan" name="satuan" list="satuan_list" class="form-control @error('satuan') is-invalid @enderror" value="{{ old('satuan', $barang->satuan ?? 'Unit') }}" required><datalist id="satuan_list">@foreach($satuan_options as $sat)<option value="{{ $sat }}"></option>@endforeach</datalist>@error('satuan')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
</div>
<div class="form-group"><label for="lokasi" class="form-label">Rak/Lokasi Detail</label><input type="text" id="lokasi" name="lokasi" class="form-control @error('lokasi') is-invalid @enderror" placeholder="Contoh: Rak A1 atau Area Elektronik" value="{{ old('lokasi', $barang->lokasi ?? '') }}" required aria-describedby="locationHelp"><div class="form-text" id="locationHelp">Keterangan posisi di dalam gudang; tidak menentukan saldo gudang.</div>@error('lokasi')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
@php($dailyUsageValue = isset($barang) && $barang->daily_usage_estimate !== null ? max(1, (int) ceil((float) $barang->daily_usage_estimate)) : '')
<div class="row"><div class="col-md-6"><div class="form-group"><label for="daily_usage_estimate" class="form-label">Estimasi Pemakaian Harian</label><input type="number" id="daily_usage_estimate" name="daily_usage_estimate" class="form-control @error('daily_usage_estimate') is-invalid @enderror" min="1" step="1" value="{{ old('daily_usage_estimate', $dailyUsageValue) }}" placeholder="Contoh: 1 atau 2" aria-describedby="dailyUsageHelp"><div class="form-text" id="dailyUsageHelp">Masukkan jumlah bulat tanpa desimal. Digunakan untuk prediksi saat belum ada transaksi keluar.</div>@error('daily_usage_estimate')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><div class="col-md-6"><div class="form-group"><label for="lead_time_days" class="form-label">Lead Time (hari)</label><select id="lead_time_days" name="lead_time_days" class="form-select @error('lead_time_days') is-invalid @enderror" aria-describedby="leadTimeHelp"><option value="">Pilih Lead Time</option>@if(isset($barang) && $barang->lead_time_days !== null && !in_array((int) $barang->lead_time_days, \App\Models\Barang::LEAD_TIME_OPTIONS, true))<option value="{{ $barang->lead_time_days }}" @selected((string) old('lead_time_days', $barang->lead_time_days) === (string) $barang->lead_time_days)>{{ $barang->lead_time_days }} hari (nilai lama)</option>@endif @foreach(\App\Models\Barang::LEAD_TIME_OPTIONS as $days)<option value="{{ $days }}" @selected((string) old('lead_time_days', $barang->lead_time_days ?? '') === (string) $days)>{{ $days }} hari</option>@endforeach</select><div class="form-text" id="leadTimeHelp">Pilih perkiraan waktu pengadaan dari supplier.</div>@error('lead_time_days')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
<div class="form-group"><label for="foto_barang" class="form-label">Foto Barang</label><input type="file" id="foto_barang" name="foto_barang" class="form-control @error('foto_barang') is-invalid @enderror" accept="image/jpeg,image/png,image/webp" aria-describedby="fotoHelp">@error('foto_barang')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text" id="fotoHelp">JPG, PNG, atau WebP maksimal 2 MB.@isset($barang) Kosongkan jika foto tidak diubah.@endisset</div>@if(isset($barang) && $barang->foto_barang)<img class="barang-photo-preview mt-2" src="{{ Storage::url($barang->foto_barang) }}" alt="Foto {{ $barang->nama_barang }}">@endif</div>
<div class="d-flex flex-wrap justify-content-end gap-2"><x-ui.button :href="route('barang.index')" variant="light">Batal</x-ui.button><x-ui.button type="submit" icon="ti-save">{{ $submitLabel }}</x-ui.button></div>
@unless(isset($barang))@push('scripts')<script>(function(){const stock=document.getElementById('stok');const warehouse=document.getElementById('warehouse_id');if(!stock||!warehouse)return;function sync(){warehouse.required=Number(stock.value)>0;}stock.addEventListener('input',sync);sync();}());</script>@endpush @endunless
